// src/lib/editor/rete/customization/presets/classic/components/Node.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { focusTrap, modeCurrent } from '@skeletonlabs/skeleton';
	// import Ref from '../../../Ref.svelte';
	// import type { ClassicScheme, SvelteArea2D } from '../types';
	import { type ClassicScheme, Ref, type SvelteArea2D } from 'rete-svelte-plugin';
	import { MacroNode } from '$rete/node/MacroNode';
	import { faCubes } from '@fortawesome/free-solid-svg-icons';
	import { XmlNode, type Node, type NodeEditorSaveData } from '$rete';
	import Fa from 'svelte-fa';
	import { EditMacroNodeChannel } from '$lib/broadcast-channels';
	import { GetGraphStore } from '$houdini';
	import { fade } from 'svelte/transition';
	type NodeExtraData = { width?: number; height?: number };

	function sortByIndex<K, I extends undefined | { index?: number }>(entries: [K, I][]) {
		entries.sort((a, b) => {
			const ai = (a[1] && a[1].index) || 0;
			const bi = (b[1] && b[1].index) || 0;
			return ai - bi;
		});
		return entries as [K, Exclude<I, undefined>][];
	}

	export let data: Node & NodeExtraData;

	$: node = data;

	const firstNameGiven = data instanceof XmlNode ? data.name : undefined;
	$: macroNode = data instanceof MacroNode ? data : undefined;
	const isMacroNode = data instanceof MacroNode;
	const isNamedXmlNode = data instanceof XmlNode && data.name !== undefined;
	// console.log('isMacroNode', isMacroNode);
	export let emit: (props: SvelteArea2D<ClassicScheme>) => void;

	$: width = Number.isFinite(data.width) ? `${data.width}px` : '';
	$: height = Number.isFinite(data.height) ? `${data.height + (isNamedXmlNode ? 15 : 0)}px` : '';

	$: inputs = sortByIndex(Object.entries(data.inputs));
	$: controls = sortByIndex(Object.entries(data.controls));
	$: outputs = sortByIndex(Object.entries(data.outputs));
	function any<T>(arg: T): unknown {
		return arg;
	}

	async function onDblClickNode() {
		console.log('Double click on node');
		if (macroNode === undefined) return;
		console.log('Double click on macro node');
		const graph = (await new GetGraphStore().fetch({ variables: { id: macroNode.graphId } })).data
			?.graph.graph;
		if (graph === undefined) throw new Error('Graph not found');
		const saveData = graph.editorData as NodeEditorSaveData;
		new EditMacroNodeChannel().postMessage({
			graph: saveData
		});
	}
	let editingName = false;
	let nameInput: HTMLInputElement | undefined;
	const disableEditing = (ev: KeyboardEvent) => {
		if (ev.key === 'Escape') editingName = false;
	};
	$: if (nameInput) {
		nameInput.focus();
		nameInput.select();
	}
	$: if (editingName) {
		document.addEventListener('keydown', disableEditing);
	} else document.removeEventListener('keydown', disableEditing);

	let startDragPos: { x: number; y: number } | undefined;
	let dragDistance: number | undefined = undefined;
	const dragThreshold = 2;
	$: if (editingName === false && isNamedXmlNode && data.name.trim() === '') {
		data.name = firstNameGiven;
	}
</script>

<div
	class="rounded-container-token node {data.selected &&
	(dragDistance === undefined || dragDistance > dragThreshold)
		? 'selected'
		: ''}"
	style:width
	style:height
	data-testid="node"
	class:bg-surface-500={!$modeCurrent}
	class:node-light-background={$modeCurrent}
>
	<div class="flex justify-between items-center">
		{#if node instanceof XmlNode && node.name !== undefined}
			<div class="title flex flex-col w-full">
				<small class="text-white text-xs opacity-60">{node.label}</small>
				<div class="relative">
					<button
						class="cursor-text text-start transition-opacity"
						class:opacity-0={editingName}
						data-testid="title"
						on:pointerdown={(event) => {
							startDragPos = { x: event.clientX, y: event.clientY };
							dragDistance = 0;
						}}
						on:pointermove={(event) => {
							if (!startDragPos) return;
							dragDistance = Math.sqrt(
								Math.pow(event.clientX - startDragPos.x, 2) +
									Math.pow(event.clientY - startDragPos.y, 2)
							);
						}}
						on:pointerup={(event) => {
							startDragPos = undefined;
							if (dragDistance && dragDistance > dragThreshold) {
								dragDistance = undefined;
								return;
							}

							dragDistance = undefined;
							if (event.button !== 0) {
								event.target.blur();
								return;
							}
							editingName = true;
							node.getFactory().selectableNodes?.unselect(node.id);
						}}
					>
						{node.name}
					</button>
					{#if editingName}
						<input
							transition:fade={{ duration: 100 }}
							bind:this={nameInput}
							class="text-token absolute top-0 left-0 w-full hover:bg-surface-50-900-token focus:bg-surface-50-900-token rounded-token dark:bg-surface-200-700-token no-border-token no-focus:border-primary-500 no-focus:ring-primary-500 transition-colors"
							type="text"
							value={node.name}
							on:blur={() => (editingName = false)}
							on:keydown={(e) => {
								if (e.key === 'Enter') editingName = false;
							}}
							on:input={(e) => {
								const val = e.target.value;
								node.name = val;
								node.setName(val);
							}}
						/>
					{/if}
				</div>
			</div>
		{:else}
			<div class="title" data-testid="title">{data.label}</div>
		{/if}
		{#if isMacroNode}
			<div
				class="p-2 text-surface-50-900-token"
				on:dblclick|preventDefault={onDblClickNode}
				on:pointerdown|stopPropagation
				role="button"
				tabindex="0"
			>
				<Fa icon={faCubes} />
			</div>
		{/if}
	</div>
	<div class="space-y-0.5">
		<!-- Outputs -->
		{#each outputs as [key, output]}
			<div class="output" data-testid={'output-' + key}>
				<div class="output-title" data-testid="output-title">
					{output.label || ''}
				</div>
				<Ref
					class="output-socket"
					data-testid="output-socket"
					init={(element) =>
						emit({
							type: 'render',
							data: {
								type: 'socket',
								side: 'output',
								key,
								nodeId: data.id,
								element,
								payload: output.socket
							}
						})}
					unmount={(ref) => emit({ type: 'unmount', data: { element: ref } })}
				/>
			</div>
		{/each}

		<!-- Controls -->
		{#each controls as [key, control]}
			<Ref
				class="control"
				data-testid={'control-' + key}
				init={(element) =>
					emit({
						type: 'render',
						data: {
							type: 'control',
							element,
							payload: control
						}
					})}
				unmount={(ref) => emit({ type: 'unmount', data: { element: ref } })}
			/>
		{/each}

		<!-- Inputs -->
		{#each inputs as [key, input]}
			<div class="rete-input text-md" data-testid={'input-' + key}>
				<Ref
					class="input-socket"
					data-testid="input-socket"
					init={(element) =>
						emit({
							type: 'render',
							data: {
								type: 'socket',
								side: 'input',
								key,
								nodeId: data.id,
								element,
								payload: input.socket
							}
						})}
					unmount={(ref) => emit({ type: 'unmount', data: { element: ref } })}
				/>
				{#if !input.control || !input.showControl}
					<div class="input-title" data-testid="input-title">
						{input.label || ''}
					</div>
				{/if}
				{#if input.control && input.showControl}
					<Ref
						class="input-control"
						data-testid="input-control"
						init={(element) =>
							emit({
								type: 'render',
								data: {
									type: 'control',
									element,
									payload: any(input).control
								}
							})}
						unmount={(ref) => emit({ type: 'unmount', data: { element: ref } })}
					/>
				{/if}
			</div>
		{/each}
	</div>
</div>

<style lang="scss">
	@use 'sass:math';
	@import '../vars';

	.node-light-background {
		background: $node-color;
	}

	.node {
		border: 2px solid #4e58bf;
		cursor: pointer;
		box-sizing: border-box;
		width: $node-width;
		height: auto;
		padding-bottom: 6px;
		position: relative;
		user-select: none;
		line-height: initial;
		font-family: Arial;
		transition: transform 0.1s;

		&.dark {
			background: darken($node-color, 4%);
		}

		&:hover {
			background: lighten($node-color, 4%);
		}

		&.selected {
			background: $node-color-selected;
			border-color: #e3c000;
		}

		.title {
			color: white;
			font-family: sans-serif;
			font-size: 18px;
			padding: 8px;
		}

		.output {
			text-align: right;
		}

		.input {
			text-align: left;
		}

		:global(.output-socket) {
			text-align: right;
			margin-right: -(math.div($socket-size, 2) + $socket-margin);
			display: inline-block;
		}

		:global(.input-socket) {
			text-align: left;
			margin-left: -(math.div($socket-size, 2) + $socket-margin);
			display: inline-block;
		}

		.input-title,
		.output-title {
			vertical-align: middle;
			color: white;
			display: inline-block;
			font-family: sans-serif;
			font-size: 14px;
			margin: $socket-margin;
			line-height: $socket-size;
		}

		:global(.input-control) {
			z-index: 1;
			width: calc(100% - #{$socket-size + 2 * $socket-margin});
			vertical-align: middle;
			display: inline-block;
		}

		:global(.control) {
			display: block;
			padding: $socket-margin math.div($socket-size, 2) + $socket-margin;
		}
	}
</style>

// src/lib/editor/rete/customization/trash/classic/components/Node.tsx
import * as React from 'react';
import styled, { css } from 'styled-components';

import { ClassicScheme, RenderEmit } from '../types';
import { $nodecolor, $nodecolorselected, $nodewidth, $socketmargin, $socketsize } from '../vars';
import { RefControl } from './refs/RefControl';
import { RefSocket } from './refs/RefSocket';

type NodeExtraData = { width?: number; height?: number };

export const NodeStyles = styled.div<
	NodeExtraData & { selected: boolean; styles?: (props: any) => any }
>`
	background: ${$nodecolor};
	border: 2px solid #4e58bf;
	border-radius: 10px;
	cursor: pointer;
	box-sizing: border-box;
	width: ${(props) => (Number.isFinite(props.width) ? `${props.width}px` : `${$nodewidth}px`)};
	height: ${(props) => (Number.isFinite(props.height) ? `${props.height}px` : 'auto')};
	padding-bottom: 6px;
	position: relative;
	user-select: none;
	line-height: initial;
	font-family: Arial;

	&:hover {
		background: lighten(${$nodecolor}, 4%);
	}
	${(props) =>
		props.selected &&
		css`
			background: ${$nodecolorselected};
			border-color: #e3c000;
		`}
	.title {
		color: white;
		font-family: sans-serif;
		font-size: 18px;
		padding: 8px;
	}
	.output {
		text-align: right;
	}
	.input {
		text-align: left;
	}
	.output-socket {
		text-align: right;
		margin-right: -${$socketsize / 2 + $socketmargin}px;
		display: inline-block;
	}
	.input-socket {
		text-align: left;
		margin-left: -${$socketsize / 2 + $socketmargin}px;
		display: inline-block;
	}
	.input-title,
	.output-title {
		vertical-align: middle;
		color: white;
		display: inline-block;
		font-family: sans-serif;
		font-size: 14px;
		margin: ${$socketmargin}px;
		line-height: ${$socketsize}px;
	}
	.input-control {
		z-index: 1;
		width: calc(100% - ${$socketsize + 2 * $socketmargin}px);
		vertical-align: middle;
		display: inline-block;
	}
	.control {
		display: block;
		padding: ${$socketmargin}px ${$socketsize / 2 + $socketmargin}px;
	}
	${(props) => props.styles && props.styles(props)}
`;

function sortByIndex<T extends [string, undefined | { index?: number }][]>(entries: T) {
	entries.sort((a, b) => {
		const ai = a[1]?.index || 0;
		const bi = b[1]?.index || 0;

		return ai - bi;
	});
}

type Props<S extends ClassicScheme> = {
	data: S['Node'] & NodeExtraData;
	styles?: () => unknown;
	emit: RenderEmit<S>;
};
export type NodeComponent<Scheme extends ClassicScheme> = (props: Props<Scheme>) => JSX.Element;

// eslint-disable-next-line max-statements
export function Node<Scheme extends ClassicScheme>(props: Props<Scheme>) {
	const inputs = Object.entries(props.data.inputs);
	const outputs = Object.entries(props.data.outputs);
	const controls = Object.entries(props.data.controls);
	const selected = props.data.selected || false;
	const { id, label, width, height } = props.data;

	sortByIndex(inputs);
	sortByIndex(outputs);
	sortByIndex(controls);

	return (
		<NodeStyles
			selected={selected}
			width={width}
			height={height}
			styles={props.styles}
			data-testid="node"
		>
			<div className="title" data-testid="title">
				{label}
			</div>
			{/* Outputs */}
			{outputs.map(
				([key, output]) =>
					output && (
						<div className="output" key={key} data-testid={`output-${key}`}>
							<div className="output-title" data-testid="output-title">
								{output?.label}
							</div>
							<RefSocket
								name="output-socket"
								side="output"
								socketKey={key}
								nodeId={id}
								emit={props.emit}
								payload={output.socket}
								data-testid="output-socket"
							/>
						</div>
					)
			)}
			{/* Controls */}
			{controls.map(([key, control]) => {
				return control ? (
					<RefControl
						key={key}
						name="control"
						emit={props.emit}
						payload={control}
						data-testid={`control-${key}`}
					/>
				) : null;
			})}
			{/* Inputs */}
			{inputs.map(
				([key, input]) =>
					input && (
						<div className="rete-input" key={key} data-testid={`input-${key}`}>
							<RefSocket
								name="input-socket"
								side="input"
								socketKey={key}
								nodeId={id}
								emit={props.emit}
								payload={input.socket}
								data-testid="input-socket"
							/>
							{input && (!input.control || !input.showControl) && (
								<div className="input-title" data-testid="input-title">
									{input?.label}
								</div>
							)}
							{input?.control && input?.showControl && (
								<RefControl
									key={key}
									name="input-control"
									emit={props.emit}
									payload={input.control}
									data-testid="input-control"
								/>
							)}
						</div>
					)
			)}
		</NodeStyles>
	);
}
