// src/rete/customization/classic/components/Socket.tsx
import * as React from 'react';
import { ClassicPreset } from 'rete';
import styled from 'styled-components';

import { $socketcolor, $socketmargin, $socketsize } from '../vars';

const Styles = styled.div`
	display: inline-block;
	cursor: pointer;
	border: 1px solid white;
	border-radius: ${$socketsize / 2.0}px;
	width: ${$socketsize}px;
	height: ${$socketsize}px;
	vertical-align: middle;
	background: ${$socketcolor};
	z-index: 2;
	box-sizing: border-box;
	&:hover {
		border-width: 4px;
	}
	&.multiple {
		border-color: yellow;
	}
`;

const Hoverable = styled.div`
	border-radius: ${($socketsize + $socketmargin * 2) / 2.0}px;
	padding: ${$socketmargin}px;
	&:hover ${Styles} {
		border-width: 4px;
	}
`;

export function Socket<T extends ClassicPreset.Socket>(props: { data: T }) {
	return (
		<Hoverable>
			<Styles title={props.data.name} />
		</Hoverable>
	);
}

// src/rete/customization/trash/classic/components/Socket.svelte
<script lang="ts">
	import type { ClassicPreset } from 'rete';

	export let data: ClassicPreset.Socket;
</script>

<div class="socket" title={data.name} />

<style lang="scss" scoped>
	@use 'sass:math';
	@import '../vars';

	.socket {
		display: inline-block;
		cursor: pointer;
		border: 1px solid white;
		border-radius: math.div($socket-size, 2);
		width: $socket-size;
		height: $socket-size;
		margin: $socket-margin;
		vertical-align: middle;
		background: $socket-color;
		z-index: 2;
		box-sizing: border-box;

		&:hover {
			border-width: 4px;
		}

		&.multiple {
			border-color: yellow;
		}

		&.output {
			margin-right: -1 * math.div($socket-size, 2);
		}

		&.input {
			margin-left: -1 * math.div($socket-size, 2);
		}
	}
</style>
