// src/rete/customization/presets/classic/components/Connection.svelte
<script lang="ts">
	import type { Position } from '../../../types';
	import type { ClassicScheme } from '../types';

	// svelte-ignore unused-export-let
	export let data: ClassicScheme['Connection'] & { isLoop?: boolean };
	// svelte-ignore unused-export-let
	export let start: Position;
	// svelte-ignore unused-export-let
	export let end: Position;
	// svelte-ignore unused-export-let
	export let targetInput: string;
	// svelte-ignore unused-export-let
	export let target: string;
	// svelte-ignore unused-export-let
	export let source: string;
	// svelte-ignore unused-export-let
	export let sourceOutput: string;
	// svelte-ignore unused-export-let
	export let id: string;
	// svelte-ignore unused-export-let
	export let path: string;
</script>

<svg data-testid="connection">
	<path d={path} />
</svg>

<style>
	/*! https://github.com/retejs/connection-plugin/commit/206ca0fd7fb82801ac45a0f7180ae05dff9ed901 */
	svg {
		overflow: visible !important;
		position: absolute;
		pointer-events: none;
		width: 9999px;
		height: 9999px;
	}

	svg path {
		fill: none;
		stroke-width: 5px;
		stroke: steelblue;
		pointer-events: auto;
	}
</style>

// src/rete/customization/classic/components/Connection.tsx
import * as React from 'react';
import styled from 'styled-components';

import { ClassicScheme } from '../types';
import { useConnection } from './ConnectionWrapper';

const Svg = styled.svg`
	overflow: visible !important;
	position: absolute;
	pointer-events: none;
	width: 9999px;
	height: 9999px;
`;

const Path = styled.path<{ styles?: (props: any) => any }>`
	fill: none;
	stroke-width: 5px;
	stroke: steelblue;
	pointer-events: auto;
	${(props) => props.styles && props.styles(props)}
`;

export function Connection(props: {
	data: ClassicScheme['Connection'] & { isLoop?: boolean };
	styles?: () => any;
}) {
	const { path } = useConnection();

	if (!path) return null;

	return (
		<Svg data-testid="connection">
			<Path styles={props.styles} d={path} />
		</Svg>
	);
}
