// src/lib/editor/rete/customization/presets/classic/components/Socket.svelte
<script lang="ts">
	import type { Socket } from '$rete/socket/Socket';
	export let data: Socket;
	import { assignColor } from '$rete/customization/utils';
	import cssVars from 'svelte-css-vars';

	let socketVars = { background: assignColor(data) };
	$: {
		socketVars = { background: assignColor(data) };
		// console.log("move to ", data.type)
	}
	// setInterval(() => {
	// 	socketVars = { background: assignColor(data) };
	// }, 200);
</script>

<div
	class="socket outline-4 outline outline-primary-400 border-white border-1 hover:border-4"
	class:array={data.isArray}
	class:outline={data.selected}
	title={data.type}
	use:cssVars={socketVars}
/>

<style lang="scss" scoped>
	@use 'sass:math';
	@import '../vars';

	.socket {
		display: inline-block;
		cursor: pointer;
		border-style: solid;
		border-radius: math.div($socket-size, 2);
		width: $socket-size;
		height: $socket-size;
		margin: $socket-margin;
		vertical-align: middle;
		background: var(--background);
		z-index: 2;
		box-sizing: border-box;

		&:hover {
			border-width: 4px;
		}

		/* &.multiple {
			border-color: yellow;
		} */

		/* &.rete-output {
			margin-right: -1 * math.div($socket-size, 2);
		}

		&.rete-input {
			margin-left: -1 * math.div($socket-size, 2);
		} */
	}
	.array {
		border: 4px dashed var(--background);
		background: none;
		border-radius: 0%;
	}
</style>

// src/rete/customization/classic/components/Socket.tsx
import * as React from 'react';
import { ClassicPreset } from 'rete';
import styled from 'styled-components';

import { $socketcolor, $socketmargin, $socketsize } from '../vars';

const Styles = styled.div`
	display: inline-block;
	cursor: pointer;
	border: 1px solid white;
	border-radius: ${$socketsize / 2.0}px;
	width: ${$socketsize}px;
	height: ${$socketsize}px;
	vertical-align: middle;
	background: ${$socketcolor};
	z-index: 2;
	box-sizing: border-box;
	&:hover {
		border-width: 4px;
	}
	&.multiple {
		border-color: yellow;
	}
`;

const Hoverable = styled.div`
	border-radius: ${($socketsize + $socketmargin * 2) / 2.0}px;
	padding: ${$socketmargin}px;
	&:hover ${Styles} {
		border-width: 4px;
	}
`;

export function Socket<T extends ClassicPreset.Socket>(props: { data: T }) {
	return (
		<Hoverable>
			<Styles title={props.data.name} />
		</Hoverable>
	);
}
