// src/rete/customization/src/presets/context-menu/components/Item.tsx
import * as React from 'react';
import styled, { css } from 'styled-components';

import { useDebounce } from '../hooks';
import { CommonStyle } from '../styles';
import { Customize, Item } from '../types';
import { $width } from '../vars';

export const ItemStyle = styled(CommonStyle)<{ hasSubitems?: boolean }>`
	${(props) =>
		props.hasSubitems &&
		css`
			&:after {
				content: '►';
				position: absolute;
				opacity: 0.6;
				right: 5px;
				top: 5px;
			}
		`}
`;

export const SubitemStyles = styled.div`
	position: absolute;
	top: 0;
	left: 100%;
	width: ${$width}px;
`;

type Props = {
	data: Item;
	delay: number;
	hide(): void;
	children: React.ReactNode;
	components?: Pick<Customize, 'item' | 'subitems'>;
};

export function ItemElement(props: Props) {
	const [visibleSubitems, setVisibleSubitems] = React.useState(false);
	const setInvisibile = React.useCallback(() => setVisibleSubitems(false), [setVisibleSubitems]);
	const [hide, cancelHide] = useDebounce(setInvisibile, props.delay);
	const Component = props.components?.item?.(props.data) || ItemStyle;
	const Subitems = props.components?.subitems?.(props.data) || SubitemStyles;

	return (
		<Component
			onClick={(e) => {
				e.stopPropagation();
				props.data.handler();
				props.hide();
			}}
			hasSubitems={Boolean(props.data.subitems)}
			onPointerDown={(e) => e.stopPropagation()}
			onPointerOver={() => {
				cancelHide();
				setVisibleSubitems(true);
			}}
			onPointerLeave={() => hide && hide()}
			data-testid="context-menu-item"
		>
			{props.children}
			{props.data.subitems && visibleSubitems && (
				<Subitems>
					{props.data.subitems.map((item) => (
						<ItemElement key={item.key} data={item} delay={props.delay} hide={props.hide}>
							{item.label}
						</ItemElement>
					))}
				</Subitems>
			)}
		</Component>
	);
}

// src/lib/editor/rete/customization/presets/context-menu/components/Item.svelte
<script lang="ts">
	import { onMount, createEventDispatcher } from 'svelte';
	import type { Item as ItemType } from '../types';
	import { debounce } from '../utils/debounce';

	const dispatch = createEventDispatcher();

	export let subitems: ItemType[] | undefined;
	export let delay: number;

	let visibleSubitems = false;
	let hide: ReturnType<typeof debounce>;

	onMount(() => {
		hide = debounce(delay, hideSubitems);
	});

	function hideSubitems() {
		visibleSubitems = false;
	}
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<!-- svelte-ignore a11y-no-static-element-interactions -->
<div
	class={'block ' + (subitems ? 'hasSubitems' : '')}
	on:click={(event) => {
		dispatch('select', event);
		dispatch('hide');
	}}
	on:wheel|stopPropagation={() => null}
	on:pointerover={() => {
		hide.cancel();
		visibleSubitems = true;
	}}
	on:pointerleave={hide.call}
	on:pointerdown|stopPropagation={() => null}
	data-testid="context-menu-item"
>
	<slot />
	{#if subitems && visibleSubitems}
		<div class="subitems">
			{#each subitems as item (item.key)}
				<svelte:self
					{item}
					on:select={() => item.handler()}
					{delay}
					on:hide={() => dispatch('hide')}
					subitems={item.subitems}
				>
					{item.label}
				</svelte:self>
			{/each}
		</div>
	{/if}
</div>

<style lang="scss">
	@import '../block';
	@import '../context-vars';

	.hasSubitems:after {
		content: '►';
		position: absolute;
		opacity: 0.6;
		right: 5px;
		top: 5px;
	}

	.subitems {
		position: absolute;
		top: 0;
		left: 100%;
		width: $width;
	}
</style>
