// src/rete/customization/src/presets/reroute-pins/Pin.tsx
import * as React from 'react';
import styled from 'styled-components';

import { useDrag } from '../../shared/drag';
import { Position } from '../../types';
import { Pin as PinType } from './types';

const pinSize = 20;

const Styles = styled.div<{ selected?: boolean }>`
	width: ${pinSize}px;
	height: ${pinSize}px;
	box-sizing: border-box;
	background: ${(props) => (props.selected ? '#ffd92c' : 'steelblue')};
	border: 2px solid white;
	border-radius: ${pinSize}px;
`;

type Props = PinType & {
	contextMenu(): void;
	translate(dx: number, dy: number): void;
	pointerdown(): void;
	pointer(): Position;
};

export function Pin(props: Props) {
	const drag = useDrag((dx, dy) => props.translate(dx, dy), props.pointer);
	const { x, y } = props.position;

	return (
		<Styles
			onPointerDown={(e) => {
				e.stopPropagation();
				e.preventDefault();
				drag.start(e);
				props.pointerdown();
			}}
			onContextMenu={(e) => {
				e.stopPropagation();
				e.preventDefault();
				props.contextMenu();
			}}
			selected={props.selected}
			style={{ position: 'absolute', top: `${y - pinSize / 2}px`, left: `${x - pinSize / 2}px` }}
			data-testid="pin"
		></Styles>
	);
}

// src/rete/customization/presets/reroute/components/Pin.svelte
<script lang="ts">
	import { createEventDispatcher, onMount } from 'svelte';
	import { useDrag } from '../../../shared/drag';
	import type { Position } from '../../../types';

	export let position: Position;
	export let selected: boolean | undefined;
	export let getPointer: () => Position;

	const pinSize = 20;
	const dispatch = createEventDispatcher();

	let drag: ReturnType<typeof useDrag>;

	function onDrag(dx: number, dy: number) {
		dispatch('translate', { dx, dy });
	}

	$: top = `${position.y - pinSize / 2}px`;
	$: left = `${position.x - pinSize / 2}px`;

	onMount(() => {
		drag = useDrag(onDrag, getPointer);
	});
</script>

<!-- svelte-ignore a11y-no-static-element-interactions -->
<div
	class="pin {selected ? 'selected' : ''}"
	style:position="absolute"
	style:top
	style:left
	data-testid="pin"
	on:contextmenu|stopPropagation|preventDefault={() => {
		dispatch('menu');
	}}
	on:pointerdown|stopPropagation|preventDefault={(event) => {
		drag.start(event);
		dispatch('down');
	}}
/>

<style lang="scss">
	$size: 20px;

	.pin {
		width: $size;
		height: $size;
		box-sizing: border-box;
		background: steelblue;
		border: 2px solid white;
		border-radius: $size;
	}

	.pin.selected {
		background: #ffd92c;
	}
</style>
