// src/rete/customization/src/presets/context-menu/components/Menu.tsx
import * as React from 'react';
import styled from 'styled-components';

import { useDebounce } from '../hooks';
import { CommonStyle } from '../styles';
import { Customize, Item } from '../types';
import { $width } from '../vars';
import { ItemElement } from './Item';
import { Search } from './Search';

export const Styles = styled.div`
	padding: 10px;
	width: ${$width}px;
	margin-top: -20px;
	margin-left: -${$width / 2}px;
`;

type Props = {
	items: Item[];
	delay: number;
	searchBar?: boolean;
	onHide(): void;
	components?: Customize;
};

export function Menu(props: Props) {
	const [hide, cancelHide] = useDebounce(props.onHide, props.delay);
	const [filter, setFilter] = React.useState('');
	const filterRegexp = new RegExp(filter, 'i');
	const filteredList = props.items.filter((item) => item.label.match(filterRegexp));
	const Component = props.components?.main?.() || Styles;
	const Common = props.components?.common?.() || CommonStyle;

	return (
		<Component
			onMouseOver={() => cancelHide()}
			onMouseLeave={() => hide && hide()}
			onWheel={(e) => e.stopPropagation()}
			data-testid="context-menu"
		>
			{props.searchBar && (
				<Common>
					<Search value={filter} onChange={setFilter} component={props.components?.search?.()} />
				</Common>
			)}
			{filteredList.map((item) => {
				return (
					<ItemElement
						key={item.key}
						data={item}
						delay={props.delay}
						hide={props.onHide}
						components={props.components}
					>
						{item.label}
					</ItemElement>
				);
			})}
		</Component>
	);
}

// src/rete/customization/presets/context-menu/components/Menu.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import type { Item as ItemType } from '../types';
	import Search from './Search.svelte';
	import Item from './Item.svelte';
	import { debounce } from '../utils/debounce';

	export let items: ItemType[];
	export let delay: number;
	export let searchBar: boolean;
	export let onHide: () => void;

	let filter = '';
	let hide: ReturnType<typeof debounce>;

	const getItems = (items: ItemType[], filter: string) => {
		const filterRegexp = new RegExp(filter, 'i');
		const filteredList = items.filter((item) => item.label.match(filterRegexp));

		return filteredList;
	};

	$: filteredList = getItems(items, filter);

	onMount(() => {
		hide = debounce(delay, onHide);
	});

	onDestroy(() => {
		if (hide) hide.cancel();
	});
</script>

<!-- svelte-ignore a11y-no-static-element-interactions -->
<!-- svelte-ignore a11y-mouse-events-have-key-events -->
<div
	class="menu rete-context-menu"
	on:mouseover={hide.cancel}
	on:mouseleave={hide.call}
	data-testid="context-menu"
>
	{#if searchBar}
		<div class="block">
			<Search text={filter} on:change={(event) => (filter = event.detail)} />
		</div>
	{/if}

	{#each filteredList as item (item.key)}
		<Item on:select={() => item.handler()} {delay} on:hide={onHide} subitems={item.subitems}>
			{item.label}
		</Item>
	{/each}
</div>

<style lang="scss">
	@use 'sass:math';
	@import '../block';
	@import '../context-vars';

	.menu {
		padding: 10px;
		width: $width;
		margin-top: -20px;
		margin-left: -(math.div($width, 2));
	}
</style>
