// src/rete/customization/src/presets/context-menu/components/Search.tsx
import * as React from 'react';
import styled from 'styled-components';

import { ComponentType } from '../types';

export const SearchInput = styled.input`
	color: white;
	padding: 1px 8px;
	border: 1px solid white;
	border-radius: 10px;
	font-size: 16px;
	font-family: serif;
	width: 100%;
	box-sizing: border-box;
	background: transparent;
`;

export function Search(props: {
	value: string;
	onChange(value: string): void;
	component?: ComponentType;
}) {
	const Component = props.component || SearchInput;

	return (
		<Component
			value={props.value}
			onInput={(e) => props.onChange((e.target as HTMLInputElement).value)}
			onPointerDown={(e) => e.stopPropagation()}
			data-testid="context-menu-search-input"
		/>
	);
}

// src/rete/customization/presets/context-menu/components/Search.svelte
<script lang="ts">
	import { createEventDispatcher } from 'svelte';

	export let text: string;

	const dispatch = createEventDispatcher();

	function handleChange(event: Event) {
		dispatch('change', (event.target as HTMLInputElement).value);
	}
</script>

<input
	class="search"
	value={text}
	on:input={handleChange}
	data-testid="context-menu-search-input"
/>

<style>
	.search {
		color: white;
		padding: 1px 8px;
		border: 1px solid white;
		border-radius: 10px;
		font-size: 16px;
		font-family: serif;
		width: 100%;
		box-sizing: border-box;
		background: transparent;
	}
</style>
