// src/lib/editor/rete/customization/Ref.svelte
<script lang="ts">
	type RefUpdate = (ref: HTMLElement) => void;

	import { onMount } from 'svelte';

	export let init: RefUpdate;
	export let unmount: RefUpdate;

	let ref: HTMLElement;

	onMount(() => {
		init(ref);
		return () => {
			unmount(ref);
		};
	});
</script>

<span {...$$restProps} bind:this={ref} />

// src/rete/customization/src/ref-component.tsx
import * as React from 'react';

type RefUpdate = (ref: HTMLElement) => void;
type BaseProps = { init: RefUpdate; unmount: RefUpdate } & Record<string, unknown>;

export function RefComponent<Props extends BaseProps>({ init, unmount, ...props }: Props) {
	const ref = React.useRef<HTMLSpanElement>(null);

	React.useEffect(() => {
		const element = ref.current;

		return () => {
			if (element) unmount(element);
		};
	}, []);
	React.useEffect(() => {
		if (ref.current) init(ref.current);
	});

	return <span {...props} ref={ref} />;
}
